services:
  apache:
    image: httpd:2.4
    container_name: web-manage
    ports:
      - "80:80"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - app
      - frontend

  app:
    build: ./app
    container_name: app-manage
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/your_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports: ["8080:8080"]
    depends_on: [mysql, mailserver]

  mysql:
    image: mysql:8.0
    container_name: db-manage
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: your_db
    ports: ["3306:3306"]
    volumes: [mysql-data:/var/lib/mysql]

  mailserver:
    image: mailhog/mailhog
    container_name: mail-manage
    ports:
      - "1025:1025"  # SMTP (送信用)
      - "8025:8025"  # Web UI (受信確認用)


  frontend:
    # image: node:alpine
    container_name: front-manage
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Vite 開発サーバーのデフォルトポート
    volumes:
      - ./frontend:/app
      - /app/node_modules 

    stdin_open: true
    tty: true

volumes:
  mysql-data: